### ISSUE TITLE
door parts A and H 

### ISSUE THREAD

**Issue by ryangadz** [TigranDesigner/Voron-Mods#1]
door parts A and H looks like they have inverted geometry. mostly printed okay except for the circular plug

**Comment by TigranDesigner** [comment]
I will check them out, do you have a screenshot of the issue, that will help me find it and fix it.

**Comment by TigranDesigner** [comment]
PS .. thanks for the feedback

**Comment by ryangadz** [comment]
![image](https://user-images.githubusercontent.com/7191784/163244031-65622e4b-157d-4714-ac66-2ea0988f0b87.png)
a quite a few are like this actually. sometimes they print fine but in this case the hole was plugged
![20220413_111438](https://user-images.githubusercontent.com/7191784/163244390-9bcac46e-39d0-4266-95d1-ce30fa3c88b0.jpg)

**Comment by TigranDesigner** [comment]
Thank you. I will fix it up tonight

**Comment by ryangadz** [comment]
I'm using Cura. Actually, A prints fine, but B is a problem strange

**Comment by TigranDesigner** [comment]
there are a few that Github shows bad but they print fine ... Regardless I will check B after work.

**Comment by TigranDesigner** [comment]
![image](https://user-images.githubusercontent.com/96996921/163508039-6ef7c787-1cd8-4fc4-9510-393056e86f05.png)
Fixed
